### ISSUE TITLE
Issue after uninstall

### ISSUE THREAD

**Issue by pine3ree** [justonestep/processwire-processlanguagetranslatortwigsupport#1]
Hello,

i uninstalled the module in 2.6.21dev (and removed the directory).

When i try to translate a new file using the default Language Translator module i get this message:

This page has no process assigned.

(the admin ulr where the message appears is admin/setup/language-translator/add/?language_id=1012)

**Comment by justb3a** [comment]
Hi, thanks. Due to the latest ProcessWire Dev branch upgrades ([2.6.23](https://processwire.com/blog/posts/processwire-2.6.23-2.7-rc2-translation-features-license-discussion/)) I updated the module and divided it in two parts. Now I extend the original process language translator module. Have a look [here](https://github.com/justonestep/processwire-languagetranslatorlist).
