### ISSUE TITLE
Question: Smarty support possible?

### ISSUE THREAD

**Issue by jmartsch** [justonestep/processwire-processlanguagetranslatortwigsupport#3]
Is there a chance that this module also supports the Smarty Engine? I am using Template Engine Factory with Template Engine Smarty and also want to edit the translation of files like  site/templates/views/myfile.tpl. Processwire only lists files with .php extension and does not look in the views directory. Can you support Smarty too or is there an easy way change this module to list my Smarty .tpl files for translation?

**Comment by justb3a** [comment]
Hi,

first of all you need another module which extends the language translator module and adds support for `.tpl` files so that such files will be listed as well. I just released a new version which adds support for `.tpl` and `.html` template files: [Language Translator List](https://github.com/justonestep/processwire-languagetranslatorlist/tree/master).

After installing this module you are able to select `.tpl` files. But you cannot translate strings. To achieve this you have to hook into the smarty template engine module and add a translation function as I did [here](https://github.com/justonestep/processwire-templatetwigreplacelanguagesupport/blob/master/TemplateTwigReplaceLanguageSupport.module#L121). I guess there is a similar way to add a function to smarty but I've never used the smarty template engine before and have not time to set up such an installation and test it. If you find a solution, I could add it to this module and change the name to a more general one – if you want me to.

**Comment by jmartsch** [comment]
Thanks for the quick adding of this feature to the Language Translator List. I take a look if I can implement the smarty translation support and let you know if so.
